# Generated by Django 4.0.3 on 2022-04-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majorapp', '0002_alter_major_name_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Subject_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='majorapp.major'),
        ),
    ]
