# Generated by Django 4.0.4 on 2022-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_visitorlog_numberview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='numberView',
            field=models.IntegerField(default=0),
        ),
    ]
