# Generated by Django 4.0.4 on 2022-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
