# Generated by Django 4.0.4 on 2022-05-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=100, verbose_name='songName')),
                ('userName', models.CharField(max_length=100, verbose_name='userName')),
            ],
        ),
        migrations.CreateModel(
            name='visitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('visitorLog', models.TextField(default='')),
                ('visitedDate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.TextField(default='')),
                ('visitorlog', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.visitorlog')),
            ],
        ),
    ]
