# Generated by Django 4.0.4 on 2022-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentName', models.CharField(max_length=100, verbose_name='USER')),
                ('commentContent', models.TextField(verbose_name='COMMENT')),
            ],
        ),
        migrations.CreateModel(
            name='songRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=100, verbose_name='songName')),
                ('userName', models.CharField(max_length=100, verbose_name='userName')),
            ],
        ),
        migrations.CreateModel(
            name='visitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitornName', models.CharField(max_length=50, verbose_name='NAME')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('visitorLog', models.TextField(default='', verbose_name='CONTENT')),
                ('visitedDate', models.DateField(default='', verbose_name='DATE')),
            ],
        ),
    ]
