# Generated by Django 4.0.4 on 2022-05-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='numberView',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
