# Generated by Django 4.0.4 on 2022-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorlog',
            old_name='visitornName',
            new_name='visitorName',
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visitedDate',
            field=models.CharField(default='', max_length=100, verbose_name='DATE'),
        ),
    ]
