# Generated by Django 4.0.4 on 2022-05-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_visitornname_visitorlog_visitorname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentName',
        ),
        migrations.AddField(
            model_name='comments',
            name='visitorLog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visitorlog', to='App.visitorlog'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentContent',
            field=models.TextField(default='', verbose_name='COMMENT'),
        ),
    ]
