# Generated by Django 4.0.4 on 2022-05-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_comments_commentname_comments_visitorlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='visitorLog',
            new_name='visitorlog',
        ),
    ]
