# Generated by Django 4.0.4 on 2022-05-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_visitorlog_comments_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='visitorlog',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitorlog', to='App.visitorlog'),
        ),
    ]
