# Generated by Django 4.0.4 on 2022-05-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_comments_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='visitorlog',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.visitorlog'),
        ),
    ]
