# Generated by Django 4.0.4 on 2022-05-22 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0006_comments_commentname_alter_visitorlog_visitorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='requestName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requestName', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsID', to=settings.AUTH_USER_MODEL),
        ),
    ]
