# Generated by Django 4.0.5 on 2022-07-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_visitorlog_likecount_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
